version: "3.9"

services:
  app:
    build: .
    container_name: healthcare-ai-assistant
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./txt_data:/app/txt_data
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
